#!/bin/sh
DEV="/dev/${MDEV}"

case "$ACTION" in
  add)
    /usr/local/bin/mount-sd "$DEV" 2>&1 | logger -t automount
    ;;
  remove)
    /usr/local/bin/umount-sd "$DEV" 2>&1 | logger -t automount
    ;;
esac
